export const STAGES = [
  {
    id: 'reveal',
    number: '01',
    title: 'Reveal',
    subtitle: 'Your Story',
    belief: 'Your story holds clues.',
    teaching: 'Every experience contains a thread of your purpose. Begin with the moments that made you feel most alive and most yourself.',
    placeholder: 'Share a moment when you felt most alive…',
    color: '#0F2A36',
    textColor: '#FFFFFF',
  },
  {
    id: 'identify',
    number: '02',
    title: 'Identify',
    subtitle: 'Your Patterns',
    belief: 'Patterns reveal purpose.',
    teaching: 'Recurring emotions, strengths, and ways you affect others are fingerprints of your purpose.',
    placeholder: 'What patterns resonate with you?',
    color: '#1A4A55',
    textColor: '#FFFFFF',
  },
  {
    id: 'pinpoint',
    number: '03',
    title: 'Pinpoint',
    subtitle: 'Your Purpose',
    belief: 'You are naming who you already are.',
    teaching: 'Your purpose statement begins with identity and ends with impact. It names who you are and how your life helps others.',
    placeholder: 'Which purpose statement feels most true?',
    color: '#2F7F7B',
    textColor: '#FFFFFF',
  },
  {
    id: 'personalize',
    number: '04',
    title: 'Personalize',
    subtitle: 'Your Season',
    belief: 'Purpose is expressed through your season.',
    teaching: 'Roles and seasons change. Purpose does not, but how you express it can change with every chapter.',
    placeholder: 'Tell me about your life right now…',
    color: '#5FA8A5',
    textColor: '#0F2A36',
  },
  {
    id: 'live',
    number: '05',
    title: 'Live',
    subtitle: 'Your Ripple',
    belief: 'Small actions create a life of purpose.',
    teaching: 'Clarity becomes powerful when it turns into action. Decide what to start, stop, and continue.',
    placeholder: 'What would you like to start, stop, or continue?',
    color: '#9FD0CD',
    textColor: '#0F2A36',
  },
  {
    id: 'expand',
    number: '06',
    title: 'Expand',
    subtitle: 'Your Growth',
    belief: 'What’s within you creates a ripple.',
    teaching: 'Purpose grows with you. Live it, return to it, and let it ripple outward.',
    placeholder: 'What are you taking away from this journey?',
    color: '#EEE9DB',
    textColor: '#0F2A36',
  },
] as const;

export const STORY_PROMPTS = [
  { id: 'alive', label: 'A moment I felt most alive' },
  { id: 'shaped', label: 'An experience that quietly shaped me' },
  { id: 'challenge', label: 'A challenge that revealed my strength' },
  { id: 'difference', label: 'A time I made a real difference' },
  { id: 'shifted', label: 'A moment when everything shifted' },
  { id: 'natural', label: 'Something I do that comes naturally' },
  { id: 'care', label: 'Something I’ve always cared about' },
  { id: 'memory', label: 'A memory I keep returning to' },
] as const;